# Generated by Django 2.0.4 on 2018-04-08 18:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('town', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField(default=None)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('deaths', models.CharField(blank=True, max_length=50, null=True)),
                ('deaths_min', models.CharField(blank=True, max_length=50, null=True)),
                ('deaths_max', models.CharField(blank=True, max_length=50, null=True)),
                ('civilians', models.CharField(blank=True, max_length=500, null=True)),
                ('injuries', models.CharField(blank=True, max_length=500, null=True)),
                ('children', models.CharField(blank=True, max_length=500, null=True)),
                ('tweet_id', models.CharField(max_length=18)),
                ('bureau_id', models.CharField(max_length=6)),
                ('bij_summary_short', models.CharField(blank=True, max_length=500, null=True)),
                ('bij_link', models.URLField(max_length=300)),
                ('target', models.CharField(blank=True, max_length=500, null=True)),
                ('articles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000000), size=None)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strike.Location')),
            ],
        ),
    ]
