# Generated by Django 2.0.4 on 2018-04-11 13:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strike.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Strike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('date', models.DateField(default=None)),
                ('narrative', models.TextField(blank=True, max_length=1000, null=True)),
                ('deaths', models.CharField(blank=True, max_length=50, null=True)),
                ('deaths_min', models.CharField(blank=True, max_length=50, null=True)),
                ('deaths_max', models.CharField(blank=True, max_length=50, null=True)),
                ('civilians', models.CharField(blank=True, max_length=50, null=True)),
                ('injuries', models.CharField(blank=True, max_length=50, null=True)),
                ('children', models.CharField(blank=True, max_length=50, null=True)),
                ('tweet_id', models.CharField(blank=True, max_length=18, null=True)),
                ('bureau_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bij_summary_short', models.TextField(blank=True, max_length=1000, null=True)),
                ('bij_link', models.URLField(blank=True, max_length=300, null=True)),
                ('target', models.CharField(blank=True, max_length=1000, null=True)),
                ('articles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000000), size=None)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strike.Location')),
            ],
        ),
    ]
