# Generated by Django 2.0.4 on 2018-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='town',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
