# Generated by Django 2.0.4 on 2018-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0002_auto_20180408_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='bureau_id',
            field=models.CharField(max_length=7),
        ),
    ]
