# Generated by Django 2.0.4 on 2018-04-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0003_auto_20180408_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='bij_summary_short',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='children',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='civilians',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='injuries',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='target',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
