# Generated by Django 2.0.4 on 2018-04-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0006_auto_20180410_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='strike',
            name='bij_summary_short',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='narrative',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
