# Generated by Django 2.0.4 on 2018-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0007_auto_20180410_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='civilians',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='deaths_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='deaths_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='injuries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
