# Generated by Django 2.0.4 on 2018-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0011_auto_20180410_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='children',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='civilians',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='deaths_max',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='deaths_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='injuries',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
