# Generated by Django 2.0.4 on 2018-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0012_auto_20180410_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strike',
            name='bij_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='bureau_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
