# Generated by Django 2.0.4 on 2018-04-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0013_auto_20180410_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
