# Generated by Django 2.0.4 on 2018-04-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0014_auto_20180410_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
