# Generated by Django 2.0.4 on 2018-04-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0015_auto_20180410_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
