# Generated by Django 2.0.4 on 2018-04-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0016_auto_20180410_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lon',
        ),
    ]
