# Generated by Django 2.0.4 on 2018-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strike', '0019_auto_20180410_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
